---
- name: Reload httpd configuration on CentOS
  command: service httpd restart
  when: ansible_distribution == "CentOS"

- name: Reload httpd configuration on Ubuntu
  command: service apache2 restart
  when: ansible_distribution == "Ubuntu"
