---
- hosts: dbservers
  become: true
  vars_files:
    - "vars.yml"
  vars:
    - httpd_port: 8080
  tasks:
  - name: Install Apache httpd
    yum: name=httpd state=present
  - name: Copy the index.html file web dir
    copy: src=index.html dest=/var/www/html/index.html
  - name: Change listen port to 8080
    lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen 80" line="Listen 8080" state=present
  - name: Restart httpd
    service: name=httpd state=restarted 
  - name: Start httpd
    service: name=httpd state=started enabled=yes
